name: Release Scripts

on:
  release:
    types:
      - created

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: .
          dest: UnityBuildTools.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: UnityBuildTools.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
