name: Release Scripts

on: 
  release:
    types: [created]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: .
          dest: UnityBuildTools.zip
      - uses: svenstaro/upload-release-action@2.2.1
        with:
          file: UnityBuildTools.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
